spring.application.name=product-crud

# Konfigurasi database akan ditambahkan saat praktikum JPA
spring.datasource.url=jdbc:postgresql://ep-quiet-credit-amyo2xsb.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_idQAL2VSgqj5
spring.datasource.driver-class-name=org.postgresql.Driver

# === Konfigurasi Database Postgresql ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true